services:
  - type: web
    name: dtip-v2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: DEMO_MODE
        value: "true"
      - key: ADMIN_EMAIL
        value: admin@dtip.co.ke
      - key: ADMIN_PASSWORD
        value: Admin@DTIP2024!
      - key: DATABASE_URL
        fromDatabase:
          name: dtip-db
          property: connectionString

databases:
  - name: dtip-db
    databaseName: dtip
    user: dtip
